# Cuaderno de Práctica: Funciones en Python para Data Science
Este cuaderno contiene ejercicios diseñados para aplicar los conceptos teóricos de la Sesión 4. 
Intenta resolver cada celda de código por tu cuenta antes de mirar las soluciones.

## Ejercicio 1: Procesamiento de Imágenes Médicas (Máscaras y `np.where`) 🩻
**Contexto:** En un proyecto de Machine Learning para detección de anomalías pulmonares, los escáneres CT se representan como matrices de densidades de píxeles (valores entre -1000 y 1000). 
**Tarea:**
1. Usando el generador aleatorio moderno (`default_rng`), crea una matriz `escaneo` de tamaño $256 \times 256$ con valores enteros aleatorios entre -1000 y 1000.
2. Los tejidos anómalos suelen tener densidades superiores a 400. Crea una máscara booleana para identificar estos píxeles.
3. Utiliza `np.where` para crear una nueva matriz `mascara_binaria` donde los píxeles sospechosos sean `1` y el resto `0`.
4. Calcula y muestra el porcentaje exacto de píxeles sospechosos en todo el escáner sin usar bucles `for`.

In [1]:
import numpy as np

rng = np.random.default_rng(2004)
np.set_printoptions(precision=4, suppress=True)
np.__version__

'2.2.6'

In [9]:
#Creamos la matriz escaneo:
escaneo = rng.integers(-1000,1000, size = (256,256))
escaneo

array([[ 420,  280,  -12, ..., -819,  484, -796],
       [ -33,  914,  825, ...,  970, -182, -119],
       [ -28,  481, -772, ...,  214, -392,   36],
       ...,
       [-989, -997, -441, ..., -994, -174,  336],
       [ 672, -169,  832, ..., -523, -670,  465],
       [ 388,  217,  447, ...,  694,   85, -859]], shape=(256, 256))

In [11]:
mask = escaneo > 400
mask

array([[ True, False, False, ..., False,  True, False],
       [False,  True,  True, ...,  True, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [ True, False,  True, ..., False, False,  True],
       [False, False,  True, ...,  True, False, False]], shape=(256, 256))

In [19]:
mascara_binaria = np.where(mask , 1 ,0)
mascara_binaria

array([[1, 0, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 0]], shape=(256, 256))

In [28]:
porcentaje = mascara_binaria.sum()/mascara_binaria.size if mascara_binaria.size > 0 else None
porcentaje

np.float64(0.2969207763671875)

## Ejercicio 2: Puntos de Equilibrio en Sistemas Dinámicos (Álgebra Lineal) 🌀
**Contexto:** Al estudiar sistemas dinámicos lineales del tipo $Ax = b$, necesitas encontrar rápidamente el punto de equilibrio en un espacio multidimensional.
**Tarea:**
1. Define la matriz de coeficientes $A$ de $4 \times 4$ y el vector constante $b$ de tamaño $4$ (inventa valores no triviales usando `np.array`).
2. Utiliza `np.linalg.solve` para encontrar el vector de estado $x$.
3. Demuestra mediante código que tu solución es correcta realizando la multiplicación matricial ($A \times x$) y usando la función `np.allclose` para compararlo con $b$.

In [19]:
#Definimos la matriz
A = np.array([[1,2,3,4],[1,2,10,1],[2,-2,3,10],[0,0,2,-3]])
b = np.array([3,4,0,-1])
A,b

A_random = rng.random((4,4))
b_random = rng.random(4) 

In [20]:
#Resolvemos:
try:
    x = np.linalg.solve(A, b)
    print("Solución única encontrada:")
    print(x)
except np.linalg.LinAlgError:
    print("Error: La matriz es singular. No existe solución única.")

try:
    x_random = np.linalg.solve(A_random,b_random)
    print("Solución única encontrada:")
    print(x_random)
except np.linalg.LinAlgError:
    print("Error: La matriz es singular. No existe solución única.")


Solución única encontrada:
[-2.6  1.   0.4  0.6]
Solución única encontrada:
[ 0.6209  1.4867 -1.6654 -0.3667]


In [44]:
#Comprobamos:
print('Los valores están muy cercanos' if np.allclose(A@x,b,rtol=0.0001) else 'Los valores están muy lejanos')
print('Los valores están muy cercanos' if np.allclose(A_random@x_random,b_random,rtol=0.0001) else 'Los valores están muy lejanos')

Los valores están muy cercanos
Los valores están muy cercanos


## Ejercicio 3: Estandarización de Progresos (Broadcasting y `axis`) 🏋️‍♂️
**Contexto:** Tienes un registro de levantamiento de pesas. Las filas representan 6 semanas de entrenamiento y las columnas representan 4 ejercicios distintos.
**Tarea:**
1. Genera una matriz `historial` de $6 \times 4$ con pesos aleatorios usando NumPy.
2. Calcula el peso máximo levantado histórico para cada ejercicio (columnas).
3. Calcula el promedio de peso levantado en cada semana (filas).
4. Utilizando **broadcasting**, crea una matriz `progreso_centrado` donde a cada registro se le reste la media histórica exclusiva de su respectivo ejercicio.

In [10]:
historial = rng.uniform(low=0,high=100,size=(6,4))
historial

array([[10.575 , 22.9084,  1.8438, 84.5166],
       [49.428 , 77.1269,  9.0965, 10.2275],
       [95.7076, 35.7045, 77.1727, 39.6783],
       [58.6484, 33.4375, 12.1693, 76.4691],
       [22.3804, 39.1145, 98.1172, 81.3061],
       [34.8234, 10.1659, 61.437 , 22.1601]])

In [31]:
pesos_maximos = historial.max(axis=0)
pesos_maximos

array([95.7076, 77.1269, 98.1172, 84.5166])

In [32]:
promedio_semana = historial.mean(axis=1)
promedio_semana

array([29.9609, 36.4697, 62.0658, 45.1811, 60.2295, 32.1466])

In [33]:
progreso_centrado = historial - historial.mean(axis=0)
progreso_centrado

array([[-34.6855, -13.5012, -41.4623,  32.1236],
       [  4.1675,  40.7173, -34.2096, -42.1654],
       [ 50.4471,  -0.7051,  33.8666, -12.7146],
       [ 13.3879,  -2.9721, -31.1368,  24.0761],
       [-22.8801,   2.7049,  54.8111,  28.9131],
       [-10.437 , -26.2437,  18.1309, -30.2328]])

## Ejercicio 4: Simulación Monte Carlo de Distribución Estelar (Random) 🌌
**Contexto:** Estás simulando la distribución de estrellas en un cúmulo globular esférico.
**Tarea:**
1. Genera una matriz de $100,000 \times 3$ que represente las coordenadas $(x, y, z)$ de posibles estrellas, usando una distribución uniforme entre -5 y 5.
2. El núcleo del cúmulo tiene un radio $R = 2.5$. Usando operaciones vectorizadas, calcula la distancia al cuadrado de cada estrella desde el origen $x^2 + y^2 + z^2$.
3. Crea un filtro para aislar únicamente las estrellas que caen dentro del núcleo esférico.
4. ¿Cuántas estrellas componen el núcleo en esta simulación? Resuélvelo usando la máscara creada.

In [37]:
N=100000
cordenadas = rng.uniform(-5,5, size=(N,3))
cordenadas

array([[-2.9562,  3.5411,  2.728 ],
       [ 4.5403, -3.3408,  1.8983],
       [-3.2339,  3.6028, -4.0953],
       ...,
       [ 1.952 , -1.479 ,  3.418 ],
       [-0.9892, -1.978 , -1.1202],
       [ 3.6915, -1.5026,  3.2219]], shape=(100000, 3))

In [39]:
distancia = cordenadas[:,0]**2 + cordenadas[:,1]**2 + cordenadas[:,2]**2
distancia

array([28.7203, 35.3783, 40.2101, ..., 17.6809,  6.1459, 26.2655],
      shape=(100000,))

In [40]:
mask = distancia < 2.5
mask

array([False, False, False, ..., False, False, False], shape=(100000,))

In [41]:
mascara_binaria = np.where(mask , 1 ,0)
mascara_binaria

array([0, 0, 0, ..., 0, 0, 0], shape=(100000,))

In [45]:
print('La cantidad de estrellas que componen el núcleo en esta simulación es: ' ,mascara_binaria.sum())

La cantidad de estrellas que componen el núcleo en esta simulación es:  1697


## Ejercicio 5: Generación y Estructuración de Señales de Audio (Reshape y Stack) 🎸
**Contexto:** Estás procesando acordes de Bossa Nova donde cada nota se representa como una matriz unidimensional de frecuencias.
**Tarea:**
1. Utiliza `np.linspace` para generar 3 arreglos diferentes de 1200 valores cada uno (representando 3 cuerdas distintas).
2. Usa `np.stack` para combinar estas 3 señales en una sola matriz de forma `(3, 1200)` (los canales son las filas).
3. Transpón la matriz resultante para que su forma sea `(1200, 3)` (formato estándar de tiempo $\times$ canales).
4. Redimensiona (`reshape`) la matriz a `(600, 6)` para simular un proceso de compresión de canales.

In [50]:
arreglo1 = np.linspace(0 , 1 , 1200)
arreglo2 = np.linspace(0 , 100 , 1200)
arreglo3 = np.linspace(0 , 50 , 1200)

In [53]:
arreglos = np.stack([arreglo1,arreglo2,arreglo3], axis = 0)
arreglos

array([[  0.    ,   0.0008,   0.0017, ...,   0.9983,   0.9992,   1.    ],
       [  0.    ,   0.0834,   0.1668, ...,  99.8332,  99.9166, 100.    ],
       [  0.    ,   0.0417,   0.0834, ...,  49.9166,  49.9583,  50.    ]],
      shape=(3, 1200))

In [54]:
arreglos_T = arreglos.T

In [56]:
arreglos_redim = arreglos_T.reshape(600,6)
arreglos_redim

array([[  0.    ,   0.    ,   0.    ,   0.0008,   0.0834,   0.0417],
       [  0.0017,   0.1668,   0.0834,   0.0025,   0.2502,   0.1251],
       [  0.0033,   0.3336,   0.1668,   0.0042,   0.417 ,   0.2085],
       ...,
       [  0.9958,  99.583 ,  49.7915,   0.9967,  99.6664,  49.8332],
       [  0.9975,  99.7498,  49.8749,   0.9983,  99.8332,  49.9166],
       [  0.9992,  99.9166,  49.9583,   1.    , 100.    ,  50.    ]],
      shape=(600, 6))

## Ejercicio 6: Distancias en Juegos de Mundo Abierto (Broadcasting Avanzado) 🏕️
**Contexto:** En un motor de simulación de supervivencia, necesitas calcular la distancia desde tu base a múltiples recursos (hierro, carbono, etc.) simultáneamente.
**Tarea:**
1. Crea un arreglo `base` con tus coordenadas $(X, Y, Z)$ de forma `(3,)`.
2. Crea una matriz `recursos` con las coordenadas de 50 ítems de forma `(50, 3)`.
3. Sin usar bucles `for`, resta las coordenadas de la base a todos los recursos simultáneamente.
4. Eleva al cuadrado el resultado, suma a través del eje correcto (`axis`) y saca la raíz cuadrada (`np.sqrt`) para obtener un arreglo unidimensional de 50 distancias exactas.

In [59]:
base = rng.uniform(0,1000,size=(3,))
base

array([392.8675, 763.4447, 604.3628])

In [61]:
recursos = rng.uniform(0,1000,size=(50,3))
recursos

array([[ 27.2956, 884.8011, 834.8888],
       [208.5516, 336.6574, 403.9047],
       [852.8622, 760.0389,  55.7805],
       [995.1725, 240.6654, 104.8767],
       [483.846 , 755.1192, 484.403 ],
       [742.9067,  79.7332, 368.5198],
       [ 24.9147, 781.217 , 103.9728],
       [270.2415, 123.0506, 303.0036],
       [153.6056,  69.1087, 677.0854],
       [744.8424, 629.3586, 600.3408],
       [358.8942, 366.8236, 658.3025],
       [505.8866, 713.7728, 504.7331],
       [336.634 , 535.4349, 356.8984],
       [849.9659, 863.3359, 883.8467],
       [ 80.1815, 174.3247,  61.4228],
       [825.1027, 326.183 , 579.6825],
       [739.514 , 577.5696, 894.0571],
       [601.8767, 565.7479,  60.9736],
       [ 83.4053, 512.0689, 905.6905],
       [  3.5442, 640.0343, 129.4357],
       [202.1413, 669.004 , 131.0513],
       [  7.9921, 530.95  , 777.6096],
       [624.3892, 211.149 , 237.2732],
       [325.2703, 683.7834,  27.462 ],
       [648.0506, 745.9642, 765.2304],
       [630.4086, 364.967

In [63]:
R = recursos - base.T
R

array([[-365.5719,  121.3564,  230.5259],
       [-184.3159, -426.7874, -200.4581],
       [ 459.9947,   -3.4058, -548.5823],
       [ 602.305 , -522.7793, -499.4861],
       [  90.9785,   -8.3256, -119.9598],
       [ 350.0392, -683.7115, -235.8431],
       [-367.9528,   17.7723, -500.39  ],
       [-122.626 , -640.3941, -301.3592],
       [-239.2619, -694.336 ,   72.7226],
       [ 351.9749, -134.0861,   -4.0221],
       [ -33.9733, -396.6211,   53.9396],
       [ 113.0191,  -49.6719,  -99.6298],
       [ -56.2335, -228.0098, -247.4645],
       [ 457.0984,   99.8912,  279.4838],
       [-312.686 , -589.12  , -542.94  ],
       [ 432.2352, -437.2617,  -24.6804],
       [ 346.6465, -185.8751,  289.6942],
       [ 209.0092, -197.6968, -543.3893],
       [-309.4622, -251.3758,  301.3276],
       [-389.3233, -123.4105, -474.9271],
       [-190.7262,  -94.4407, -473.3115],
       [-384.8755, -232.4947,  173.2467],
       [ 231.5216, -552.2957, -367.0896],
       [ -67.5972,  -79.6613, -576

In [66]:
final = np.sqrt((R**2).sum(axis = 1))
final

array([448.9013, 506.264 , 715.9255, 941.0398, 150.7872, 803.4991,
       621.3657, 718.3029, 737.9955, 376.6718, 401.7113, 158.6402,
       341.1588, 545.0031, 860.0109, 615.3326, 488.5039, 614.8502,
       499.7549, 626.3853, 518.9599, 481.8686, 702.4156, 586.2848,
       302.1628, 683.3088, 620.2954, 567.8775, 352.8045, 577.6105,
       607.2411, 600.0588, 727.1798, 652.1719, 574.1955, 422.1907,
       924.0317, 897.2962, 543.177 , 398.7305, 635.5793, 544.424 ,
       395.731 , 994.9048, 733.8385, 344.3804, 796.6754, 381.9114,
       689.6445, 274.6587])

## Ejercicio 7: Mapas de Calor Tácticos (Outliers, `argmax` y `clip`) ⚽
**Contexto:** Analizas el mapa de calor (posesión de balón) en una cuadrícula del campo de fútbol.
**Tarea:**
1. Crea una cuadrícula `campo` de $10 \times 10$ con valores aleatorios extraídos de una distribución normal estándar (`rng.standard_normal`).
2. Algunos valores pueden ser ruido estadístico extremo. Usa `np.clip` para limitar todos los valores del campo a un rango entre -1.5 y 1.5.
3. Encuentra el valor de intensidad máxima de posesión en la cuadrícula ya recortada.
4. Utiliza `np.argmax` y `np.unravel_index` para imprimir la coordenada exacta `(fila, columna)` donde ocurre esta intensidad máxima.

In [72]:
campo = rng.standard_normal(size=(10,10))
campo

array([[-0.6929, -0.3111,  0.5222,  0.4121, -0.7843,  0.6051,  1.5361,
         0.355 , -0.7998,  0.3831],
       [ 0.5809, -1.0381, -0.7166,  0.0353, -0.8672,  0.5196, -0.0748,
        -1.0431, -0.4523,  1.2765],
       [ 0.2002,  1.1282, -1.113 ,  1.4418, -0.0016,  0.5098,  0.0989,
         0.2769,  0.8918,  0.4504],
       [ 2.2925,  1.4725, -0.0222, -0.3695,  0.8307,  0.632 , -0.7297,
         0.1376,  0.9972,  0.2616],
       [ 0.3664,  0.1246, -0.6051,  2.1806, -1.1   ,  1.2498, -0.6072,
         0.4276, -1.8524,  1.7738],
       [-0.3238, -2.5309,  1.5196,  0.2994,  0.4704, -0.6512, -0.4038,
        -0.9109, -2.4968,  1.3552],
       [-1.1724,  1.0857, -0.3235,  0.5141,  0.421 ,  0.5166,  0.8432,
         0.1104, -1.9504, -1.221 ],
       [ 0.6297, -0.9586,  0.5901, -0.3394, -0.2784,  0.7015, -1.1256,
         1.045 ,  0.0781,  0.6989],
       [ 0.0546, -0.5428, -0.585 ,  0.3599, -0.5324,  0.6363, -0.1686,
         0.2307, -0.427 ,  1.2628],
       [-0.1503, -2.5627, -0.7921,  0

In [74]:
campo_f = np.clip(campo , -1.5 , 1.5)
campo_f

array([[-0.6929, -0.3111,  0.5222,  0.4121, -0.7843,  0.6051,  1.5   ,
         0.355 , -0.7998,  0.3831],
       [ 0.5809, -1.0381, -0.7166,  0.0353, -0.8672,  0.5196, -0.0748,
        -1.0431, -0.4523,  1.2765],
       [ 0.2002,  1.1282, -1.113 ,  1.4418, -0.0016,  0.5098,  0.0989,
         0.2769,  0.8918,  0.4504],
       [ 1.5   ,  1.4725, -0.0222, -0.3695,  0.8307,  0.632 , -0.7297,
         0.1376,  0.9972,  0.2616],
       [ 0.3664,  0.1246, -0.6051,  1.5   , -1.1   ,  1.2498, -0.6072,
         0.4276, -1.5   ,  1.5   ],
       [-0.3238, -1.5   ,  1.5   ,  0.2994,  0.4704, -0.6512, -0.4038,
        -0.9109, -1.5   ,  1.3552],
       [-1.1724,  1.0857, -0.3235,  0.5141,  0.421 ,  0.5166,  0.8432,
         0.1104, -1.5   , -1.221 ],
       [ 0.6297, -0.9586,  0.5901, -0.3394, -0.2784,  0.7015, -1.1256,
         1.045 ,  0.0781,  0.6989],
       [ 0.0546, -0.5428, -0.585 ,  0.3599, -0.5324,  0.6363, -0.1686,
         0.2307, -0.427 ,  1.2628],
       [-0.1503, -1.5   , -0.7921,  0

In [77]:
pos = np.unravel_index(campo_f.argmax(), campo_f.shape)
pos

(np.int64(0), np.int64(6))

In [78]:
print("max global:", campo_f[pos], "en", pos)

max global: 1.5 en (np.int64(0), np.int64(6))


## Ejercicio 8: Vistas vs Copias en Métricas Académicas (Slicing) 📊
**Contexto:** Procesas los puntajes de un curso dividido en 3 bloques de estudio (Ej: LEAN4, Python, MATLAB).
**Tarea:**
1. Crea una matriz `puntajes` de $5 \times 3$ con notas (enteros del 0 al 20).
2. Extrae un bloque que contenga solo las filas de la 1 a la 3 y las primeras dos columnas, y asígnalo a la variable `sub_puntajes`.
3. Suma 2 puntos de bonificación directamente a todos los elementos de `sub_puntajes`.
4. Imprime la matriz `puntajes` original. ¿Se modificó? Ahora, repite el proceso pero asegúrate de extraer una **copia** para que la bonificación no afecte los registros originales. Demuestra ambas situaciones en código.

In [101]:
puntajes = rng.integers(0 , 20 , size = (5,3))
puntajes

array([[17, 11, 10],
       [13, 11, 10],
       [14, 10,  4],
       [16, 19,  1],
       [11,  9,  4]])

In [102]:
sub_puntajes = puntajes[:3,:2]
sub_puntajes

array([[17, 11],
       [13, 11],
       [14, 10]])

In [103]:
sub_puntajes = sub_puntajes + 2
sub_puntajes

array([[19, 13],
       [15, 13],
       [16, 12]])

In [100]:
puntajes

array([[17,  1,  4],
       [ 5, 12,  3],
       [ 5,  1, 12],
       [12, 19, 15],
       [13,  3,  2]])